import {chromium} from 'playwright';import assert from 'node:assert/strict';import http from 'node:http';import {readFileSync} from 'node:fs';
const host='http://127.0.0.1:8765',errors=[];let checks=0;
const control=data=>new Promise((resolve,reject)=>{const req=http.request('http://127.0.0.1:8766/test/control',{method:data?'POST':'GET',headers:{'Content-Type':'application/json'}},res=>{let s='';res.on('data',c=>s+=c);res.on('end',()=>resolve(JSON.parse(s)));});req.setTimeout(5000,()=>req.destroy(new Error('fixture timeout')));req.on('error',reject);req.end(data?JSON.stringify(data):undefined);});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{
const context=await browser.newContext({viewport:{width:1365,height:900},permissions:['clipboard-read','clipboard-write']});
await context.route('**/*',async route=>{const url=route.request().url();if(url.endsWith('/assets/vendor/supabase.js'))return route.fulfill({contentType:'application/javascript',body:`window.supabase={createClient(){let listeners=[];const session=()=>localStorage.getItem('signedout')?null:{access_token:localStorage.getItem('account')==='b'?'fixture-b':'fixture-a',user:{id:localStorage.getItem('account')==='b'?'22222222-2222-4222-8222-222222222222':'11111111-1111-4111-8111-111111111111',email:localStorage.getItem('account')==='b'?'b@example.test':'a@example.test',user_metadata:{full_name:localStorage.getItem('account')==='b'?'Account B':'Account A'}}};return{auth:{getSession:async()=>({data:{session:session()}}),refreshSession:async()=>({data:{session:session()}}),signOut:async()=>{localStorage.setItem('signedout','1');listeners.forEach(f=>f('SIGNED_OUT',null));return{};},onAuthStateChange:fn=>{listeners.push(fn);return{data:{subscription:{unsubscribe(){}}}};}}}}};`});
 if(url.includes('three@0.160.0/build/three.module.js'))return route.fulfill({contentType:'application/javascript',body:readFileSync(new URL('./node_modules/three/build/three.module.js',import.meta.url))});
 if(!url.startsWith(host)&&!url.startsWith('blob:')&&!url.startsWith('data:'))return route.abort();return route.continue();});
await context.addInitScript(()=>{const seen=new WeakSet(),raf=window.requestAnimationFrame.bind(window);window.requestAnimationFrame=fn=>{if(seen.has(fn))return 0;seen.add(fn);return raf(fn);};});const page=await context.newPage();page.setDefaultTimeout(12000);const waitFunction=page.waitForFunction.bind(page);page.waitForFunction=(fn,arg,options={})=>waitFunction(fn,arg,{polling:100,...options});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?'Renamed browser chat':undefined));
const wait=async fn=>{await page.waitForFunction(fn,null,{timeout:20000});};const ok=(v)=>{assert.ok(v);checks++;};
await page.goto(host+'/chat');await page.locator('#user-profile-bar').waitFor({state:'visible'});console.log('browser: authenticated');
await control({delay:3500});await page.locator('#kurama-input').fill('My name is Browser User.');await page.locator('#kurama-input').press('Enter');await page.locator('[data-job-state]').waitFor();ok(await page.locator('.bot-reply-text').count()===0);await page.waitForTimeout(700);ok(await page.locator('.bot-reply-text').count()===0);
console.log('browser: generation indicator');const firstChat=await page.locator('.chat-item.active').getAttribute('data-chat-id');await page.locator('#btn-new-chat').click();await page.waitForFunction(id=>document.querySelector('.chat-item.active')?.dataset.chatId!==id,firstChat);ok(await page.locator('.bot-reply-text').count()===0);console.log('browser: new chat');await page.locator(`[data-chat-id="${firstChat}"] .chat-item-main`).click();console.log('browser: reopened chat');await page.reload();console.log('browser: reloaded');await wait(()=>document.querySelectorAll('.bot-reply-text').length===1);ok((await page.locator('.bot-reply-text').textContent()).includes('one'));ok(await page.locator('.bot-reply-text script').count()===0);ok(await page.evaluate(()=>window.evil)!==true);ok(await page.locator('.table-wrapper table').count()===1);ok(await page.locator('pre .code-language').textContent()==='python');ok(await page.locator('pre code .hljs-built_in').count()>0);ok(await page.locator('.bot-reply-text a').getAttribute('rel')==='noopener noreferrer');console.log('browser: full response, reload, markdown');await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));ok(await page.locator('.chat-row').count()===0);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await wait(()=>document.querySelectorAll('.bot-reply-text').length===1);ok(true);
await page.locator('pre .message-action').click();ok(await page.locator('pre .message-action').textContent()==='Copied ✓');ok(await page.evaluate(()=>navigator.clipboard.readText())==='print("Hello")\n');await page.locator('.chat-row.bot .message-actions button').filter({hasText:/^Copy$/}).click();const copied=await page.evaluate(()=>navigator.clipboard.readText());ok(copied.includes('Full answer.\n'));ok(!copied.includes('Regenerate'));
await control({delay:250});await page.getByRole('button',{name:'Regenerate',exact:true}).click();await wait(()=>!document.querySelector('[data-job-state]'));ok(await page.locator('.chat-row.user').count()===1);ok(await page.locator('.bot-reply-text').count()===1);
await page.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('.message-editor').fill('My name is Edited User.');await page.getByRole('button',{name:'Save & Submit',exact:true}).click();await wait(()=>document.querySelector('.user-message-text')?.textContent==='My name is Edited User.'&&!document.querySelector('[data-job-state]'));ok(await page.locator('.chat-row.user').count()===1);
await page.locator('#btn-open-memory').click();await page.locator('.memory-item-value').filter({hasText:'Edited User'}).waitFor();ok(true);await page.locator('#btn-close-memory').click();
await page.locator('#attachment-input').setInputFiles({name:'example.py',mimeType:'text/x-python',buffer:Buffer.from('print(42)')});await page.waitForFunction(()=>document.querySelector('#attachment-drafts')?.textContent.includes('example.py')&&!document.querySelector('#attachment-drafts')?.textContent.includes('uploading'));ok(await page.locator('#attachment-drafts .attachment-chip').count()===1);await page.locator('#kurama-input').fill('Explain attached code');await page.locator('#kurama-input').press('Enter');await wait(()=>document.querySelectorAll('.chat-row.user').length===2&&!document.querySelector('[data-job-state]'));ok(await page.locator('.message-attachments').count()===1);ok(await page.locator('#attachment-drafts .attachment-chip').count()===0);
await control({delay:15000});await page.locator('#kurama-input').fill('Long reply');await page.locator('#kurama-input').press('Enter');await page.waitForFunction(()=>document.querySelector('[data-job-state]')?.textContent.includes('Thinking'));await page.waitForTimeout(800);console.log('browser: stopping');await page.locator('#btn-stop-generation').click();await page.getByRole('button',{name:'Continue',exact:true}).waitFor();ok(true);await control({delay:200});await page.getByRole('button',{name:'Continue',exact:true}).click();await wait(()=>!document.querySelector('[data-job-state]')&&!Array.from(document.querySelectorAll('button')).some(b=>b.textContent==='Continue'));ok(await page.locator('.chat-row.user').count()===3);
await control({delay:2500});await page.locator('#kurama-input').fill('Finish after leaving');await page.locator('#kurama-input').press('Enter');await page.locator('[data-job-state]').waitFor();await page.goto(host+'/');await page.waitForTimeout(3000);await page.goto(host+'/chat');await wait(()=>document.querySelectorAll('.bot-reply-text').length===4);ok(true);console.log('browser: actions, attachments, background navigation');
await page.locator('.chat-item.active [title="Rename chat"]').click();await page.locator('.chat-item-main').filter({hasText:'Renamed browser chat'}).waitFor();await page.locator('#chat-search').fill('Renamed');await page.waitForTimeout(400);ok(await page.locator('.chat-item').count()===1);
await page.setViewportSize({width:390,height:844});await page.locator('#btn-sidebar-toggle').click();ok(await page.locator('#chat-sidebar').evaluate(n=>n.classList.contains('open')));await page.locator('.chat-item-main').click();ok(!(await page.locator('#chat-sidebar').evaluate(n=>n.classList.contains('open'))));await page.waitForTimeout(500);await page.screenshot({path:'tests/chat-mobile.png'});await page.setViewportSize({width:1365,height:900});await page.waitForTimeout(400);await page.screenshot({path:'tests/chat-desktop.png'});
await page.locator('#btn-logout').click();await page.waitForURL(host+'/');await page.evaluate(()=>{localStorage.setItem('account','b');localStorage.removeItem('signedout');});await page.goto(host+'/chat');await page.locator('#user-profile-bar').waitFor({state:'visible'});ok(await page.locator('.chat-row').count()===0);ok(!(await page.locator('#chat-history-list').textContent()).includes('Renamed'));ok(await page.locator('#attachment-drafts').textContent()==='');ok(!errors.length);console.log(`${checks} browser assertions passed`);
}catch(e){for(const context of browser.contexts())for(const p of context.pages()){console.log('browser failure:',await p.locator('#toast-pill').textContent().catch(()=>''));console.log((await p.locator('#kurama-chat-body').innerText().catch(()=>'' )).slice(0,2000));console.log('page errors',errors);console.log('model stats',JSON.stringify(await control()).slice(0,250));await p.screenshot({path:'tests/browser-failure.png'}).catch(()=>{});}throw e;}finally{await browser.close();}
