// Test-only PostgreSQL/Supabase/Ollama fixture. Never loaded by the application.
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';import http from 'node:http';import {fileURLToPath} from 'node:url';
export const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
export async function setup(){const db=new PGlite();await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE SCHEMA storage;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint);CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text,name text);ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;CREATE FUNCTION storage.foldername(text) RETURNS text[] LANGUAGE sql AS $$ SELECT string_to_array($1,'/') $$;GRANT USAGE ON SCHEMA public,auth,storage TO anon,authenticated,service_role;GRANT ALL ON storage.objects TO anon,authenticated,service_role;INSERT INTO auth.users VALUES('${A}'),('${B}');`);await db.exec(readFileSync(new URL('../supabase/SETUP.sql',import.meta.url),'utf8'));return db;}
export async function rpc(db,name,args){const keys=Object.keys(args);return (await db.query(`SELECT public.jai_${name}(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) AS value`,Object.values(args))).rows[0].value;}
export async function asUser(db,uid,sql,args=[]){return db.transaction(async tx=>{await tx.exec('SET LOCAL ROLE authenticated');await tx.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[uid]);return tx.query(sql,args);});}
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const db=await setup(),files=new Map();let delay=700,fail=false,vision=false,inflight=0,maxInflight=0,cancelled=0;const payloads=[];
 const server=http.createServer(async(req,res)=>{let chunks=[];for await(const c of req)chunks.push(c);const bytes=Buffer.concat(chunks),url=new URL(req.url,'http://localhost'),token=(req.headers.authorization||'').replace('Bearer ','');const uid=token==='fixture-a'?A:token==='fixture-b'?B:null,service=token==='fixture-service';let data;try{data=bytes.length?JSON.parse(bytes):null;}catch{}
 const send=(status,obj)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(obj));};
 try{
 if(url.pathname==='/test/control'){if(data){if('delay'in data)delay=data.delay;if('fail'in data)fail=data.fail;if('vision'in data)vision=data.vision;}return send(200,{inflight,maxInflight,cancelled,payloads});}
 if(url.pathname==='/auth/v1/user')return uid?send(200,{id:uid,email:uid===A?'a@example.test':'b@example.test'}):send(401,{});
 if(url.pathname==='/api/show')return send(200,{capabilities:vision?['completion','vision']:['completion']});
 if(url.pathname==='/api/chat'){
  if(!data.stream)return send(200,{message:{content:data.format?'{}':'OK'},done:true});
  payloads.push(data);inflight++;maxInflight=Math.max(maxInflight,inflight);let ended=false;res.on('close',()=>{inflight--;if(!ended)cancelled++;});
  if(fail){ended=true;return send(500,{error:'mock'});}res.writeHead(200,{'Content-Type':'application/x-ndjson'});res.write(JSON.stringify({message:{content:'Full answer.\n\n```python\nprint("Hello")\n```\n\n'},done:false})+'\n');
  setTimeout(()=>{if(res.destroyed)return;ended=true;res.end(JSON.stringify({message:{content:'| A | B |\n|---|---|\n| one | two |\n\n[Safe link](https://example.com)\n<script>window.evil=true</script>'},done:true})+'\n');},delay);return;
 }
 if(url.pathname.startsWith('/storage/v1/')){if(!service)return send(403,{});const prefix='/storage/v1/object/';if(req.method==='DELETE'){for(const p of data.prefixes)files.delete('chat-attachments/'+p);return send(200,[]);}let path=decodeURIComponent(url.pathname.slice(prefix.length)).replace(/^authenticated\//,'');if(req.method==='POST'){files.set(path,bytes);return send(200,{Key:path});}if(files.has(path)){res.writeHead(200);return res.end(files.get(path));}return send(404,{});}
 if(!url.pathname.startsWith('/rest/v1/')||(!service&&!uid))return send(401,{});
 const path=url.pathname.slice('/rest/v1/'.length);
 if(path.startsWith('rpc/')){if(!service)return send(403,{});const name=path.slice(8);if(!/^\w+$/.test(name))throw new Error('bad');if(name==='search'){const out=await db.query('SELECT * FROM public.jai_search($1,$2,$3)',[data.p_user,data.p_query,data.p_offset||0]);return send(200,out.rows);}return send(200,await rpc(db,name,data));}
 if(!/^[a-z_]+$/.test(path))return send(404,{});let values=[],where=[];const add=v=>{values.push(v);return '$'+values.length;};for(const [k,v]of url.searchParams){if(['select','order','limit','offset','on_conflict'].includes(k))continue;if(!/^\w+$/.test(k))throw new Error('bad');const i=v.indexOf('.'),op=v.slice(0,i),val=v.slice(i+1);if(op==='eq')where.push(`${k}=${add(val)}`);else if(['lt','lte','gt','gte'].includes(op))where.push(`${k}${{lt:'<',lte:'<=',gt:'>',gte:'>='}[op]}${add(val)}`);else if(op==='is'&&val==='null')where.push(`${k} IS NULL`);else if(op==='in')where.push(`${k} IN (${val.slice(1,-1).split(',').map(add).join(',')})`);else throw new Error('bad filter');}
 let sql,params;
 if(req.method==='GET'){const cols=url.searchParams.get('select')||'*';if(!/^[\w,*]+$/.test(cols))throw new Error('bad');sql=`SELECT ${cols} FROM public.${path}`+(where.length?' WHERE '+where.join(' AND '):'');const order=url.searchParams.get('order');if(order){sql+=' ORDER BY '+order.split(',').map(s=>{const [c,dir]=s.split('.');if(!/^\w+$/.test(c)||!['asc','desc'].includes(dir))throw new Error('bad');return c+' '+dir;}).join(',');}sql+=' LIMIT '+Math.min(Number(url.searchParams.get('limit')||1000),1000)+' OFFSET '+Number(url.searchParams.get('offset')||0);params=values;}
 else if(req.method==='POST'){if(!service)return send(403,{});const keys=Object.keys(data);if(keys.some(k=>!/^\w+$/.test(k)))throw new Error('bad');params=Object.values(data);sql=`INSERT INTO public.${path}(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')})`;const prefer=req.headers.prefer||'';if(prefer.includes('ignore-duplicates'))sql+=' ON CONFLICT DO NOTHING';if(prefer.includes('merge-duplicates')){const conflict=url.searchParams.get('on_conflict')||'id';if(!/^[\w,]+$/.test(conflict))throw new Error('bad');sql+=' ON CONFLICT('+conflict+') DO UPDATE SET '+keys.filter(k=>!conflict.split(',').includes(k)).map(k=>`${k}=excluded.${k}`).join(',');}sql+=' RETURNING *';}
 else if(req.method==='PATCH'){if(!service)return send(403,{});const sets=Object.entries(data).map(([k,v])=>`${k}=${add(v)}`);sql=`UPDATE public.${path} SET ${sets.join(',')} WHERE ${where.join(' AND ')} RETURNING *`;params=values;}
 else if(req.method==='DELETE'){if(!service)return send(403,{});sql=`DELETE FROM public.${path}`+(where.length?' WHERE '+where.join(' AND '):'')+' RETURNING *';params=values;}
 const out=service?await db.query(sql,params):await asUser(db,uid,sql,params);return send(200,out.rows);
 }catch(e){return send(400,{message:e.message,code:e.code||'fixture'});}
 });server.listen(8766,'127.0.0.1',()=>console.log('fixture ready'));}
